/** Canonical v2 flat column block (~106 columns). */
export const POLICY_CSV_FLAT_HEADERS = [
  "year",
  "month",
  "grouping",
  "Customer ID",
  "SVKK ID",
  "Holder name",
  "Holder PAN",
  "Holder Aadhaar",
  "previous policy no",
  "PRE. END DATE",
  "policy no",
  "Policy start",
  "Policy end",
  "Person Count*",
  "Insurance company",
  "TPA",
  "Product Type",
  "Village",
  "Category",
  "Holder DOB",
  "Holder gender",
  "Holder age",
  "Holder relationship",
  "Persons insured",
  "Sum insured",
  "holder cumulative bonus",
  "holder joining year",
  "holder basic premium",
  "Gross premium",
  "Tax %",
  "Tax amount",
  "SVKK premium",
  "Net premium",
  "VKK commission",
  "Commission amount",
  "Policy Holder Premium",
  "Two lac floater",
  "Gaam mahajan contribution",
  "Excess / short",
  "Diff paid by holder",
  "loan_status",
  "loan_amt",
  "cd_account_status",
  "cd_amount",
  "Refund Cheque Amount",
  "Refund Cheque Number",
  "Refund Cheque Date",
  "Member 1 Name",
  "Member 1 DOB",
  "Member 1 Relationship",
  "Member 1 Gender",
  "MEMBER 1 DATE OF JOINING",
  "Member 1 Sum insured",
  "Member 1 Basic premium",
  "Member 1 Cumulative bonus",
  "Member 1 Phone",
  "Member 1 Age at entry",
  "nominee_name",
  "nominee_relation",
  "nominee mobile",
  "Address Line 1: House/Flat No, Building Name",
  "Address Line 2: Street/Road Name",
  "Address Line 3: Landmark / Locality",
  "Address Line 4: Additional Details (optional)",
  "area",
  "city",
  "pincode",
  "Primary Mobile Number",
  "Secondary Mobile Number",
  "whatsapp",
  "email",
  "Courier Status",
  "courier_date",
  "courier_address",
  "pod",
  "Courier Company",
  "gen remark",
  "policy remarK",
  "ref no",
  "Created at",
  "Updated at",
  "policy url",
  "url",
] as const;

export type PolicyCsvFlatHeader = (typeof POLICY_CSV_FLAT_HEADERS)[number];
