import type { AdMemberRow } from "./ad-member-types";

export type AdPolicyPaymentModeForm = "ONLINE" | "CHEQUE" | "CASH";
export type AdPolicyTransactionModeForm = "ONLINE" | "CHEQUE" | "CASH" | "NEFT";

export type AdPolicyPaymentTransactionForm = {
  mode: AdPolicyTransactionModeForm;
  transactionNumber: string;
  bankName: string;
  branch: string;
  accountNumber: string;
  nameAsPerCheque: string;
  ifscCode: string;
  notOver: string;
  transactionDate: string;
  transactionStatus: "CLEARED" | "DISHONOURED" | "PENDING" | "";
  dishonourReason: string;
  returnCharges: string;
  amountReceived: string;
};

export type AdPolicyFormValues = {
  policyNo: string;
  adProduct: string;
  customerId: string;
  svkkPublicId: string;
  policyHolder: string;
  /** UI-only: legacy HTML "HOLDER GENDER"; not persisted (InsuredParty has no gender column). */
  holderGender: string;
  panNo: string;
  company: string;
  tpa: string;
  previousPolicyNo: string;
  previousEndDate: string;
  policyGroup: string;
  policyStart: string;
  policyEnd: string;
  village: string;
  cat: string;
  dob: string;
  age: string;
  relation: string;
  holderJoiningDate: string;
  holderAddOns: string;
  person: string;
  sumInsured: string;
  comulativeBonus: string;
  joiningYear: string;
  basicPremiumPs: string;
  members: AdMemberRow[];
  paymentMode: AdPolicyPaymentModeForm;
  onlineTransactionRef: string;
  policyChequeNo: string;
  bank: string;
  accountNo: string;
  branch: string;
  nameAsPerCheque: string;
  ifsc: string;
  notOver: string;
  chequeDate: string;
  chequeStatus: string;
  reasonDishonoured: string;
  paymentTransactions: AdPolicyPaymentTransactionForm[];
  vkkPremium: string;
  coPremium: string;
  grossPremium: string;
  taxPercent: string;
  taxAmount: string;
  svkkPremiumCalc: string;
  netPremiumCalc: string;
  vkkCommission: string;
  contribution: string;
  differenceAmountPaidByHolder: string;
  commission: string;
  twoLakhF: string;
  policyHolderPremium: string;
  gaamMahajan: string;
  excessShort: string;
  diffAmt: string;
  loanStatus: string;
  loanNo: string;
  loanAmt: string;
  nomineeName: string;
  nomineeRelation: string;
  nomineePhoneNumber: string;
  address: string;
  addressTwo: string;
  addressThree: string;
  addressFour: string;
  area: string;
  city: string;
  pincode: string;
  mobileFirst: string;
  mobileSecond: string;
  whatsappNo: string;
  email: string;
  refundChequeAmt: string;
  refundChequeNo: string;
  refundChequeDate: string;
  cdAccountStatus: string;
  cdAmount: string;
  notCourier: string;
  courierDate: string;
  courierCompany: string;
  podNumber: string;
  courierAddress: string;
  generalRemark: string;
  policyChangeRemark: string;
  refNo: string;
  year: string;
  month: string;
  policyGrouping: string;
  url: string;
};

export function getAdPolicyInitialValues(): AdPolicyFormValues {
  return {
    policyNo: "",
    adProduct: "",
    customerId: "",
    svkkPublicId: "",
    policyHolder: "",
    holderGender: "",
    panNo: "",
    company: "",
    tpa: "",
    previousPolicyNo: "",
    previousEndDate: "",
    policyGroup: "",
    policyStart: "",
    policyEnd: "",
    village: "",
    cat: "",
    dob: "",
    age: "",
    relation: "",
    holderJoiningDate: "",
    holderAddOns: "",
    person: "1",
    sumInsured: "",
    comulativeBonus: "",
    joiningYear: "",
    basicPremiumPs: "",
    members: [],
    paymentMode: "CHEQUE",
    onlineTransactionRef: "",
    policyChequeNo: "",
    bank: "",
    accountNo: "",
    branch: "",
    nameAsPerCheque: "",
    ifsc: "",
    notOver: "",
    chequeDate: "",
    chequeStatus: "",
    reasonDishonoured: "",
    paymentTransactions: [
      {
        mode: "ONLINE",
        transactionNumber: "",
        bankName: "",
        branch: "",
        accountNumber: "",
        nameAsPerCheque: "",
        ifscCode: "",
        notOver: "",
        transactionDate: "",
        transactionStatus: "",
        dishonourReason: "",
        returnCharges: "",
        amountReceived: "",
      },
    ],
    vkkPremium: "",
    coPremium: "",
    grossPremium: "",
    taxPercent: "",
    taxAmount: "",
    svkkPremiumCalc: "",
    netPremiumCalc: "",
    vkkCommission: "",
    contribution: "",
    differenceAmountPaidByHolder: "",
    commission: "",
    twoLakhF: "",
    policyHolderPremium: "",
    gaamMahajan: "",
    excessShort: "",
    diffAmt: "",
    loanStatus: "",
    loanNo: "",
    loanAmt: "",
    nomineeName: "",
    nomineeRelation: "",
    nomineePhoneNumber: "",
    address: "",
    addressTwo: "",
    addressThree: "",
    addressFour: "",
    area: "",
    city: "",
    pincode: "",
    mobileFirst: "",
    mobileSecond: "",
    whatsappNo: "",
    email: "",
    refundChequeAmt: "",
    refundChequeNo: "",
    refundChequeDate: "",
    cdAccountStatus: "",
    cdAmount: "",
    notCourier: "",
    courierDate: "",
    courierCompany: "",
    podNumber: "",
    courierAddress: "",
    generalRemark: "",
    policyChangeRemark: "",
    refNo: "",
    year: "",
    month: String(new Date().getMonth() + 1),
    policyGrouping: "",
    url: "",
  };
}
