import type { Prisma } from "@prisma/client";

/** Fields returned by GET /claims/:id and accepted on PATCH. */
export const claimDetailSelect = {
  id: true,
  claimNo: true,
  svkkPublicId: true,
  policyYear: true,
  policyId: true,
  patientName: true,
  patientAge: true,
  patientRelation: true,
  patientGender: true,
  mdId: true,
  categoryText: true,
  status: true,
  statusText: true,
  claimType: true,
  actualLodgeType: true,
  treatmentType: true,
  treatmentProcedure: true,
  diseaseCategory: true,
  claimAmount: true,
  reportedLodgeAmount: true,
  approvedAmount: true,
  deductionAmount: true,
  discountAmount: true,
  deductionDetails: true,
  remark: true,
  balanceSumInsured: true,
  village: true,
  tpaName: true,
  insuranceCompany: true,
  doBranch: true,
  policyHolderName: true,
  policyTypeText: true,
  policyNoText: true,
  policyGroupingText: true,
  policyStartDate: true,
  policyEndDate: true,
  sumInsured: true,
  claimReceivedDate: true,
  informationRaisedDate: true,
  informationReceivedDate: true,
  hospitalName: true,
  hospitalArea: true,
  networkType: true,
  hospitalInPpn: true,
  admissionDate: true,
  dischargeDate: true,
  lodgeDate: true,
  illness: true,
  deniedReasons: true,
  roomCategory: true,
  paymentDetails: true,
  paymentInFavourOf: true,
  paymentDate: true,
  prsCrsDate: true,
  matchStatus: true,
  events: {
    orderBy: [{ sourceRowNumber: "asc" }, { createdAt: "asc" }],
    select: {
      id: true,
      sourceRowNumber: true,
      kind: true,
      outcome: true,
      rejectionReason: true,
      claimType: true,
      actualLodgeType: true,
      statusText: true,
      claimAmount: true,
      reportedLodgeAmount: true,
      approvedAmount: true,
      deductionAmount: true,
      admissionDate: true,
      lodgeDate: true,
      paymentDate: true,
      paymentDetails: true,
      paymentInFavourOf: true,
      remark: true,
      createdAt: true,
    },
  },
  policy: {
    select: {
      policyNo: true,
      policyType: { select: { id: true, key: true, name: true } },
    },
  },
} satisfies Prisma.ClaimSelect;

export type ClaimDetailRow = Prisma.ClaimGetPayload<{ select: typeof claimDetailSelect }>;
