import type { Prisma } from "@prisma/client";

/** Fields returned by GET /claims/:id and accepted on PATCH. */
export const claimDetailSelect = {
  id: true,
  claimNo: true,
  svkkPublicId: true,
  policyYear: true,
  policyId: true,
  patientName: true,
  patientAge: true,
  patientRelation: true,
  patientGender: true,
  status: true,
  statusText: true,
  claimType: true,
  claimAmount: true,
  approvedAmount: true,
  deductionAmount: true,
  deductionDetails: true,
  balanceSumInsured: true,
  village: true,
  tpaName: true,
  insuranceCompany: true,
  doBranch: true,
  policyHolderName: true,
  policyTypeText: true,
  policyStartDate: true,
  policyEndDate: true,
  sumInsured: true,
  claimReceivedDate: true,
  informationRaisedDate: true,
  informationReceivedDate: true,
  hospitalName: true,
  hospitalArea: true,
  networkType: true,
  hospitalInPpn: true,
  admissionDate: true,
  dischargeDate: true,
  illness: true,
  deniedReasons: true,
  roomCategory: true,
  paymentDetails: true,
  matchStatus: true,
  policy: { select: { policyNo: true } },
} satisfies Prisma.ClaimSelect;

export type ClaimDetailRow = Prisma.ClaimGetPayload<{ select: typeof claimDetailSelect }>;
