export type ClaimDetail = {
  id: string;
  claimNo: string;
  svkkPublicId: string;
  policyYear: string;
  policyId?: string | null;
  patientName?: string | null;
  patientAge?: number | null;
  patientRelation?: string | null;
  patientGender?: string | null;
  status: string;
  statusText?: string | null;
  claimType?: string | null;
  claimAmount?: string | number | null;
  approvedAmount?: string | number | null;
  deductionAmount?: string | number | null;
  deductionDetails?: string | null;
  balanceSumInsured?: string | number | null;
  village?: string | null;
  tpaName?: string | null;
  insuranceCompany?: string | null;
  doBranch?: string | null;
  policyHolderName?: string | null;
  policyTypeText?: string | null;
  policyStartDate?: string | null;
  policyEndDate?: string | null;
  sumInsured?: string | number | null;
  claimReceivedDate?: string | null;
  informationRaisedDate?: string | null;
  informationReceivedDate?: string | null;
  hospitalName?: string | null;
  hospitalArea?: string | null;
  networkType?: string | null;
  hospitalInPpn?: boolean | null;
  admissionDate?: string | null;
  dischargeDate?: string | null;
  illness?: string | null;
  deniedReasons?: string | null;
  roomCategory?: string | null;
  paymentDetails?: string | null;
  matchStatus?: string | null;
  policy?: { policyNo: string | null } | null;
};
